# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "zhao"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

template: "template_toolkit"
engines:
   template_toolkit:
     encoding:  'utf8'
     start_tag: '[%'
     end_tag:   '%]'

session: Simple

plugins:
  DBIC:
    default:
      schema_class: zhaoapi::Schema
      connect_info:
        - "DBI:mysql:zhao:182.92.131.59:3306"
        - zhaoyao
        - panwujie
        - AutoCommit: 1
          RaiseError: 1
          PrintError: 1

	# dbicdump -o dump_directory=./Schema \
 #         -o components='["InflateColumn::DateTime"]' \
 #         -o debug=1 \
 #         zhaoapi::Schema \
 #         'DBI:mysql:zhao:182.92.131.59:3306' \
 #         zhaoyao \
 #         panwujie


